version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/var/www
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=base64:cs6sSoC/LtksNGqCzBO/JeN5TF4TmlVP2OO9oBOlxlM=
      - DB_CONNECTION=mysql
      - DB_HOST=192.168.184.215
      - DB_PORT=3306
      - DB_DATABASE=dinkes_tegal
      - DB_USERNAME=siola
      - DB_PASSWORD=s10l4apP
