version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/var/www
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=base64:YOUR_APP_KEY_HERE
      - DB_CONNECTION=mysql
      - DB_HOST=dpg-cu86c8bv2p9s73c83lpg-a
      - DB_PORT=5432
      - DB_DATABASE=siola
      - DB_USERNAME=siola_user
      - DB_PASSWORD=BRXu74efmT6crROMWTaqddSYmMfRC9OM

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: siol4
      MYSQL_DATABASE: dinkes_tegal
      MYSQL_USER: siola
      MYSQL_PASSWORD: s10l4apP
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
