services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    buildCommand: ""
    startCommand: ""
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:cs6sSoC/LtksNGqCzBO/JeN5TF4TmlVP2OO9oBOlxlM=
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: 192.168.184.215
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: dinkes_tegal
      - key: DB_USERNAME
        value: siola
      - key: DB_PASSWORD
        value: s10l4apP
